version: '3'
services:

  spring-boot-app:
      build:
        context: ./back-end
        dockerfile: Dockerfile
      ports:
        - "8080"
        
  react-app:
      build:
        context: ./front-end
        dockerfile: Dockerfile
      ports:
        - "3000"