pipeline {
    environment {
        registry = "oppie2024/back-end"
        registryCreditials ="dockerhub_id"
        dockerImage =""
    }
    agent any
        stages {   
            stage ('Build Docker Image') {           
                steps {
                    dir('back-end'){
                    script {
                        dockerImage = docker.build(registry)
                        }
                    }
                }
            }            
            stage ("Push to Docker Hub") {
                steps {
                    script {
                        docker.withRegistry('', registryCreditials) {
                            dockerImage.push("${env.BUILD_NUMBER}")
                            dockerImage.push("latest")
                        }
                    }
                }
            }            
        }    
}